---
name: Package build

on:
  workflow_dispatch:
    inputs:
      create_release:
        description: 'True to create release from tag'
        required: true
        type: boolean
      tags:
        description: 'Tag to create'
        required: true
        type: string
  push:
    branches:
      - main
    paths-ignore:
      - '.github/'
      - 'README.md'
      - 'docker/'
      - 'k2plus-default/'

jobs:
  build:
    name: Binary build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Building Binaries
        run: |
          echo "SHORT_SHA=`git rev-parse --short HEAD`" >> $GITHUB_ENV
          ./build.sh

      - name: Generate Token
        uses: tibdex/github-app-token@v2
        id: generate-token
        with:
          app_id: ${{ secrets.zaggbot_app_id }}
          private_key: ${{ secrets.zaggbot_app_private_key }}

      - name: Create release and upload artifacts
        uses: ncipollo/release-action@v1
        if: ${{ inputs.create_release }}
        with:                                                                                                                                                                                       
          token: "${{ steps.generate-token.outputs.token }}"
          artifactErrorsFailBuild: true
          generateReleaseNotes: true
          tag: ${{ inputs.tags }} 
          name: v${{ inputs.tags }} 
          artifacts: "./release/filament-sync-tool_*"
          body: |
            NOTE
            --------------------------------------                                                                                                                                                  
            Windows release is detected as a virus.                                                                                                                                                 
            You can trust me or not but it is not a Virus.                                                                                                                                          
                                                                                                                                                                                                    
            Most of the time if the program is not signed, it is flagged in Windows.                                                                                                                
            You can read more about it here:                                                                                                                                                        
            https://go.dev/doc/faq#virus

      - name: Create pre-release and upload artifacts
        uses: ncipollo/release-action@v1
        with:
          token: "${{ steps.generate-token.outputs.token }}"
          artifactErrorsFailBuild: true
          generateReleaseNotes: true
          prerelease: true
          tag: pre-${{ env.SHORT_SHA }}
          commit: ${{ env.GITHUB_SHA }}
          name: "latest dev pre-release"
          artifacts: "./release/filament-sync-tool_*"
          body: |
            pre-release build ${{ env.SHORT_SHA }}
            --------------------------------------  
            Windows release is detected as a virus.  
            You can trust me or not but it is not a Virus.  

            Most of the time if the program is not signed, it is flagged in Windows.  
            You can read more about it here:  
            https://go.dev/doc/faq#virus
